### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by sudeshna-d** [zalandoresearch/flair#122]
Hi, I am trying to install flair, but the installation fails with the following message. I have rwx permission for /usr/local/man/man1

Can anyone please help me with issue?

```
Installing collected packages: tqdm, segtok, flair
  Found existing installation: tqdm 4.26.0
    Uninstalling tqdm-4.26.0:
      Successfully uninstalled tqdm-4.26.0
  Rolling back uninstall of tqdm
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, a/usr/local/man/man1rgs)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 376, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 315, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/man/man1'

```

**Comment by alanakbik** [comment]
Hi, we've never seen this error before. But looking at the error message some ideas: 

1. It seems that you are using Python 3.5 - you should use Python 3.6+ for Flair. If you're on Ubuntu 16.04 you can set up Python 3.6 [like this](http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/). Newer versions of Ubuntu directly ship with 3.6+ I believe. 

2. Could it be that you are not installing into a virtual environment? We generally recommend setting up a Python3 virtualenv and then doing pip install there. So, once you have Python 3.6+ set up, do 

```
virtualenv --python=[path/to/python3.6] [path/to/this/virtualenv]

source [path/to/this/virtualenv]/bin/activate

pip install flair
```

Does this help?

**Comment by sudeshna-d** [comment]
@alanakbik  Thanks a lot! I can't believe I missed the Python 3.6 requirement in the docs.
