### ISSUE TITLE
Generate text with language model

### ISSUE THREAD

**Issue by djstrong** [zalandoresearch/flair#167]
Is there any script that can generate text from trained language model?
Also calculating perplexity on testing data would be helpful.

**Comment by alanakbik** [comment]
Hi @djstrong you can point the following script to a language model that you've trained with Flair: 

```python
import torch
from flair.models import LanguageModel

dataset = '/path/to/your/lm/best-lm.pt'

# load the language model
model = LanguageModel.load_language_model(dataset)

idx2item = model.dictionary.idx2item

# initial hidden state
hidden = model.init_hidden(1)
input = torch.rand(1, 1).mul(len(idx2item)).long()

# generate text character by character
characters = []
number_of_characters_to_generate = 2000
for i in range(number_of_characters_to_generate):
    prediction, rnn_output, hidden = model.forward(input, hidden)
    word_weights = prediction.squeeze().data.div(1.0).exp().cpu()
    word_idx = torch.multinomial(word_weights, 1)[0]
    input.data.fill_(word_idx)
    word = idx2item[word_idx].decode('UTF-8')
    characters.append(word)

    if i % 100 == 0:
        print('| Generated {}/{} chars'.format(i, number_of_characters_to_generate))

# print generated text
print(''.join(characters))
```

This generates 2000 characters. I think in a future release, we will add such code directly to the `LanguageModel` class to make this easier!

**Comment by djstrong** [comment]
Thank you, it works. However, after more than 100 characters there is `CUDA error: out of memory`.

**Comment by stefan-it** [comment]
@alanakbik I tried an own language model, but the generation method above gives the following error message:

```bash
Traceback (most recent call last):
  File "generate.py", line 19, in <module>
    prediction, rnn_output, hidden = model.forward(input, hidden)
  File "/mnt/flair/flair/models/language_model.py", line 66, in forward
    encoded = self.encoder(input)
  File "/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 110, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #3 'index'
```

Using the latest version from `master`, can you help?

**Comment by stefan-it** [comment]
Thanks Alan, this is working for me:

```python
import torch
from flair.models import LanguageModel

dataset = 'best-lm.pt'

# load the language model
model = LanguageModel.load_language_model(dataset)

model = model.cuda()

idx2item = model.dictionary.idx2item

# initial hidden state
hidden = model.init_hidden(1)
input = torch.rand(1, 1).mul(len(idx2item)).long().cuda()

# generate text character by character
characters = []
number_of_characters_to_generate = 500
for i in range(number_of_characters_to_generate):
    prediction, rnn_output, hidden = model.forward(input, hidden)
    word_weights = prediction.squeeze().data.div(1.0).exp().cpu()
    word_idx = torch.multinomial(word_weights, 1)[0]
    input.data.fill_(word_idx)
    word = idx2item[word_idx].decode('UTF-8')
    characters.append(word)

    if i % 100 == 0:
        print('| Generated {}/{} chars'.format(i, number_of_characters_to_generate))

# print generated text
print(''.join(characters))
```

**Comment by alanakbik** [comment]
@mhham Thanks for the pointer! I'll open an issue!
