### ISSUE TITLE
Running into error (potentially unrelated to Flair): Segmentation fault

### ISSUE THREAD

**Issue by pwichmann** [zalandoresearch/flair#168]
Hi all,

I am running into a **segmentation fault** in my script that mainly just uses flair (0.3.1). Interestingly, it does not immediately run into the error but runs perfectly fine for a few minutes before it crashes.

This may be totally unrelated to Flair - but my traceback error stack does not provide me with more information.

If anyone else has the same problem, could you digitally raise your hand?

Ubuntu 16.04
Flair 0.3.1 (problem also occurs with 0.3.0)
Python 3.6

Error stack (faulthandler):

```
Fatal Python error: Segmentation fault

Current thread 0x00007f866d53a700 (most recent call first):
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 288 in forward
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 324 in forward
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192 in forward
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477 in __call__
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/models/language_model.py", line 71 in forward
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/models/language_model.py", line 100 in get_representation
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/embeddings.py", line 521 in _add_embeddings_internal
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/embeddings.py", line 48 in embed
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/embeddings.py", line 115 in embed
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 182 in forward
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 449 in _predict_scores_batch
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 435 in predict
  File "/home/pascal/xyz/mvp_pipeline/production_system/ner/ner_flair.py", line 79 in flair_returnDictForTokenisedSentenceAsString
  File "/home/pascal/xyz/mvp_pipeline/production_system/ner/ner_ensemble.py", line 20 in returnNERresult
  File "main.py", line 111 in process_single_text_file
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/multiprocessing/pool.py", line 44 in mapstar
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/threading.py", line 864 in run
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/pascal/anaconda3/envs/NLP_preprocessing/lib/python3.6/threading.py", line 884 in _bootstrap

Segmentation fault (core dumped)
```

**Comment by pwichmann** [comment]
GDB error traceback:

```
Thread 11 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffeab977700 (LWP 7525)]
0x00007fffd425152b in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
```

Backtrace:

```
#0  0x00007fffd425152b in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007fffd43897b6 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fffd416e9de in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fffd416eba3 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fffd42c5610 in cuLaunchKernel () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fffacf4e561 in cudart::cudaApiLaunchCommon(void const*, bool) ()
   from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#6  0x00007fffacf6c16d in cudaLaunch () from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#7  0x00007fffad194be6 in __device_stub__Z21sgemm_32x32x32_NN_vecPfS_S_ffiiiiiiii(float*, float*, float*, float, float, int, int, int, int, int, int, int, int) ()
   from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#8  0x00007fffad0c9b7c in cublasSgemm_openai_kernel(cublasContext&, cublasStatus_t&, cublasOperation_t, cublasOperation_t, int, int, int, float const*, float const*, int, float const*, int, float const*, float*, int, int) () from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#9  0x00007fffad0513b2 in cublasSgemmRecursiveEntry(cublasContext*, int, int, int, int, int, float const*, float const*, int, float const*, int, float const*, float*, int) () from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#10 0x00007fffad0c110c in cublasSgemmEx () from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#11 0x00007fffae064196 in cublasSgemmExRecursiveEntry(cublasContext*, int, int, int, int, int, float const*, void const*, cudaDataType_t, int, void const*, cudaDataType_t, int, float const*, void*, cudaDataType_t, int, cublasGemmAlgo_t) ()
   from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#12 0x00007fffad8bbd6b in RNNForwardPass<float, float, float>::run(cudnnContext*, cudnnRNNStruct*, int, PerfOptions, forwardMode, cudnnTensorStruct* const*, void const*, void const*, void const*, void const*, void*, void*, void*, void*, unsigned long, void*, unsigned long) ()
   from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#13 0x00007fffad8af694 in cudnnRNNForwardGeneric(cudnnContext*, cudnnRNNStruct*, int, cudnnTensorStruct* const*, void const*, cudnnTensorStruct*, void const*, cudnnTensorStruct*, void const*, cudnnFilterStruct*, void const*, cudnnTensorStruct* const*, void*, cudnnTensorStruct*, void*, cudnnTensorStruct*, void*, void*, unsigned long, void*, unsigned long, forwardMode) () from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#14 0x00007fffad8b087f in cudnnRNNForwardInference () from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#15 0x00007fffaa9c1dad in at::native::_cudnn_rnn(at::Tensor const&, at::ArrayRef<at::Tensor>, long, at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, long, bool, double, bool, bool, at::ArrayRef<long>, at::Tensor const&) ()
   from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#16 0x00007fffaac45790 in at::Type::_cudnn_rnn(at::Tensor const&, at::ArrayRef<at::Tensor>, long, at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long, long, bool, double, bool, bool, at::ArrayRef<long>, at::Tensor const&) const ()
   from /home/pascal/anaconda3/envs/NLP_preprocessing_v2/lib/python3.6/site-packages/torch/lib/libATen.so
#17 0x00007fffca3e2696 in torch::autograd::VariableType::_cudnn_rnn (this=<optimised out>, input=..., weight=..., weight_stride0=<optimised out>, weight_buf=..., 
    hx=..., cx=..., mode=2, hidden_size=256, num_layers=1, batch_first=false, dropout=<optimised out>, train=false, bidirectional=true, batch_sizes=..., 
    dropout_state=...) at torch/csrc/autograd/generated/VariableType.cpp:17847
#18 0x00007fffca477a68 in at::_cudnn_rnn (dropout_state=..., batch_sizes=..., bidirectional=true, train=false, dropout=0, batch_first=false, num_layers=1, 
    hidden_size=256, mode=2, cx=..., hx=..., weight_buf=..., weight_stride0=4, weight=..., input=...)
    at /opt/conda/conda-bld/pytorch_1524584710464/work/torch/lib/tmp_install/include/ATen/Functions.h:2921
#19 torch::autograd::dispatch__cudnn_rnn (dropout_state=..., batch_sizes=..., bidirectional=true, train=false, dropout=0, batch_first=false, num_layers=1, 
    hidden_size=256, mode=2, cx=..., hx=..., weight_buf=..., weight_stride0=4, weight=..., input=...)
    at torch/csrc/autograd/generated/python_torch_functions_dispatch.h:341
#20 torch::autograd::THPVariable__cudnn_rnn (self=<optimised out>, args=<optimised out>, kwargs=<optimised out>)
    at torch/csrc/autograd/generated/python_torch_functions.cpp:575
#21 0x00007ffff796608d in _PyCFunction_FastCallDict (func_obj=func_obj@entry=0x7fffd521faf8, args=args@entry=0x7ffe981e3df0, nargs=<optimised out>, 
    kwargs=kwargs@entry=0x0) at Objects/methodobject.c:231
#22 0x00007ffff7966315 in _PyCFunction_FastCallKeywords (func=func@entry=0x7fffd521faf8, stack=stack@entry=0x7ffe981e3df0, nargs=<optimised out>, 
    kwnames=kwnames@entry=0x0) at Objects/methodobject.c:294
#23 0x00007ffff79ff49a in call_function (pp_stack=pp_stack@entry=0x7ffeab974100, oparg=oparg@entry=15, kwnames=kwnames@entry=0x0) at Python/ceval.c:4830
#24 0x00007ffff7a0371c in _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3328
[...]
```

**Comment by pwichmann** [comment]
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCTensorCopy.cu line=100 error=11 : invalid argument
*** Error in `/home/pascal/anaconda3/envs/NLP_preprocessing_v2/bin/python': double free or corruption (fasttop): 0x00007ffea0033830 ***
```

**Comment by pwichmann** [comment]
It's very weird because the script runs perfectly well for a handful of minutes before it crashes.

I also increased stack size and file number size via ulimit.

**Comment by pwichmann** [comment]
@alanakbik 

You were right. It looks like a single thread does not show this problematic behaviour. Even though I don't know what is causing the crash.

Feel free to close this issue.
