### ISSUE TITLE
`math range error` during training a language model

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#180]
Hi,

I'm using the latest version from `master` and tried to train a language model using the latest `master` version from `pytorch`.

Ppl looked very strange:
 
```bash
2018-10-29 17:29:17,905 | split   6 / 44 |   100/  391 batches | ms/batch 93.51 | loss 512.26 | ppl 2949330234204888195092094283304872706170763573927698779075425692296989315294879965116933993802270221224859889413802073155760928864335945078287073424076994233424775515952242800785527058311672721141903289338033849838715535360.00
2018-10-29 17:29:27,152 | split   6 / 44 |   200/  391 batches | ms/batch 92.47 | loss 527.19 | ppl 9073203143751104391241102323602781830078113776867388089379525425862210996630970230313274603911892887361812721899836154227539755005435944866505268264141309209059623967567629396406993464522987491518453555540939309198468607136235520.00
2018-10-29 17:29:36,424 | split   6 / 44 |   300/  391 batches | ms/batch 92.72 | loss 573.01 | ppl 714739889762914961342673376780803557021656542891157699453249659846965864820350996347987334174611533875376549211982228477865709852492006222301815492121553730925580806767903725102591258113864956871918043820141709584027318125691900549772892795295498240.00
2018-10-29 17:29:44,884 training done! 	(17:29:44)
2018-10-29 17:29:46,281 best loss so far 99.90
2018-10-29 17:29:46,281 -----------------------------------------------------------------------------------------
2018-10-29 17:29:46,281 | end of split   6 / 44 | epoch   1 | time: 37.73s | valid loss 587.47 | valid ppl 1366353960485726755859484864187687380286018741512508887960786243904356880165917352732685778158027445618189877097272364496434012376746287488940117722657989790910311245159130071330577833687783624875092744667739699898365864542189931509904467654721745488707584.00 | learning rate 20.00
2018-10-29 17:29:46,281 -----------------------------------------------------------------------------------------
2018-10-29 17:29:46,281 Split 7	 - (17:29:46)
2018-10-29 17:30:50,631 	(17:30:50)
2018-10-29 17:30:59,916 | split   7 / 44 |   100/  394 batches | ms/batch 92.85 | loss 598.80 | ppl 114063686399820653642816178891763508521244068871462514743454226629578648347395008379181110786451796600130083648258389596028261604292946609930735168968679728646409765243561062064195513707859989799783696869255278700479093011543702737898403159892133741463223664640.00
2018-10-29 17:31:09,140 | split   7 / 44 |   200/  394 batches | ms/batch 92.24 | loss 615.39 | ppl 1818803028524699276392664865326367830652419686835046002372326650960639844309159687632274079912630485545532896323998202812523292620978431192291894360727871518671868356162538846366088021401090445135328556581065297765145755387932550581316888975087861556050462513031020544.00
2018-10-29 17:31:18,383 | split   7 / 44 |   300/  394 batches | ms/batch 92.43 | loss 653.90 | ppl 96411063649468070337756347065934824814758281670187894009374568337244581030764287330769932069729697338837684498527459402674257884413287689067393229255343892303397844725394662732233802165717752287878004490184425680023210229280502256739180822540315976835450021035301894311708901372854272.00
2018-10-29 17:31:27,048 training done! 	(17:31:27)
```

And then the following error message occured:

```bash
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    max_epochs=50)
  File "/mnt/flair/flair/trainers/language_model_trainer.py", line 255, in train
    math.exp(cur_loss)))
OverflowError: math range error
```

Is this `pytorch` related? I have an own compiled version of PyTorch because I need CUDA 10 for my GPU :)

**Comment by alanakbik** [comment]
It might be PyTorch related. I remember an error like this (gigantic perplexity numbers) a long while back that somehow just disappeared after some torch updates on our cluster. 

Does the error also happen when you set a much smaller initial learning rate, say 1.0?

**Comment by stefan-it** [comment]
Hm, with the latest `pytorch` (47c0d88) it is working :fireworks: (here's the commit [comparison](https://github.com/pytorch/pytorch/compare/4d62eef...47c0d88) between the version I tried first and current `master` of `pytorch`).

So I'm closing here :)
