### ISSUE TITLE
Frozen dropout in LM embeddings

### ISSUE THREAD

**Issue by alanakbik** [zalandoresearch/flair#184]
The current implementation of `CharLMEmbeddings` applies the dropout from `LanguageModel` in training mode to randomly drop out 50% of dimensions. However, since embeddings are in most settings saved into memory/disk during the first epoch, they do not get recomputed, meaning that the randomly dropped out fields are "frozen" throughout each epoch. This is undesirable since we would like dropout to be re-applied randomly at each epoch. 

Solution: Exclude `CharLMEmbeddings` from recursive `torch.train()` call (i.e. make sure it always has dropout turned off) and apply dropout afterwards. This has the added bonus of making dropout behavior consistent across all embeddings classes.

**Comment by alanakbik** [comment]
Hi @qiuwei, the easiest way to do this right now would be to follow the instructions [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md) and use the version of Flair and the parameters that we specify there.  

Since we moved things around a bit since then, otherwise you would need to do another parameter sweep (and probably wait until we fix the above bug) to get similar numbers.

**Comment by alanakbik** [comment]
Ah and wrt the cache it should not affect performance, so if it does this would be an error. However, the results you posted all look pretty similar - each run will always give slightly different results depending on random seeds, dropout etc., which is why we typically repeat each experiment 5 times to get an average score.

**Comment by qiuwei** [comment]
Hi Alan, thanks for the quick response.

I think adding self.eval() to the get_representation() in the language model could be a fix to the problem you mentioned.

BTW, the 0.2.0 version specified in the documents doesn't work due to some bugs:
```
Traceback (most recent call last):
  File "conll.py", line 8, in <module>
    corpus: TaggedCorpus = NLPTaskDataFetcher.fetch_data(NLPTask.CONLL_2000)
  File "/home/qiuwei.cw/Projects/flair/flair/data_fetcher.py", line 56, in fetch_data
    sentence.convert_tag_scheme(tag_type='np', target_scheme='iobes')
  File "/home/qiuwei.cw/Projects/flair/flair/data.py", line 282, in convert_tag_scheme
    tags = iob_iobes(tags)
  File "/home/qiuwei.cw/Projects/flair/flair/data.py", line 501, in iob_iobes
    raise Exception('Invalid IOB format!')
Exception: Invalid IOB format!
```

**Comment by alanakbik** [comment]
Oha strange. Does this happen only for CoNLL 2000 or also for the other datasets, i.e. CoNLL-03 etc.?

**Comment by qiuwei** [comment]
@alanakbik  sorry, my bad. I put the used the conll 2000 data reader for 2003 data.
