### ISSUE TITLE
fastText portuguese (pt) embeddings

### ISSUE THREAD

**Issue by ericlief** [zalandoresearch/flair#231]
When I try to download the packaged 'pt' embeddings like so, I get a builtins value error (array shape) 

from flair.data_fetcher import NLPTaskDataFetcher
from flair.embeddings import CharLMEmbeddings, WordEmbeddings, StackedEmbeddings
from typing import List, Dict
from flair.data import Span, Token, Label
from collections import defaultdict

fh = "/home/liefe/data/pt/harem/data/HAREM"
cols = {0:"text", 1:"ne"}    
corpus = NLPTaskDataFetcher.fetch_column_corpus(fh,
                                                cols,
                                                train_file="train.txt",
                                                dev_file="dev.txt",
                                                test_file="test.txt").downsample(.3)

# Load Character Language Models (clms)
clm_fw = CharLMEmbeddings("/home/liefe/lm/fw_p25/best-lm.pt") 
clm_bw = CharLMEmbeddings("/home/liefe/lm/bw_p25/best-lm.pt")   

# Load festText word embeddings
word_embedding = WordEmbeddings("pt")
tag_type = "ne"

# Make the tag dictionary from the corpus
tag_dict = corpus.make_tag_dictionary(tag_type=tag_type)

# Construct the tagger
from flair.models import SequenceTagger

tagger = SequenceTagger(hidden_size=256,
            embeddings=stacked_embedding,
            tag_dictionary=tag_dict,
            tag_type=tag_type,
            use_crf=True)

from flair.trainers import SequenceTaggerTrainer

trainer = SequenceTaggerTrainer(tagger, corpus)
trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=150,
              patience=25,
              embeddings_in_memory=False) # I've tried true and false here

File "/home/liefe/code/sequence-tagger/sequence-tagger/test-spans.py", line 98, in <module>   word_embedding = WordEmbeddings("pt") File "/home/liefe/anaconda3/envs/gpu/lib/python3.6/site-packages/flair-0.3.1-py3.6.egg/flair/embeddings.py", line 180, in __init__   self.precomputed_word_embeddings = gensim.models.KeyedVectors.load(embeddings) File "/home/liefe/anaconda3/envs/gpu/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 122, in load   return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs) File "/home/liefe/anaconda3/envs/gpu/lib/python3.6/site-packages/gensim/utils.py", line 426, in load   obj._load_specials(fname, mmap, compress, subname) File "/home/liefe/anaconda3/envs/gpu/lib/python3.6/site-packages/gensim/utils.py", line 467, in _load_specials   val = np.load(subname(fname, attrib), mmap_mode=mmap) File "/home/liefe/anaconda3/envs/gpu/lib/python3.6/site-packages/numpy/lib/npyio.py", line 433, in load   pickle_kwargs=pickle_kwargs) File "/home/liefe/anaconda3/envs/gpu/lib/python3.6/site-packages/numpy/lib/format.py", line 698, in read_array   array.shape = shape 

builtins.ValueError: cannot reshape array of size 204692448 into shape (999999,300)

**Comment by alanakbik** [comment]
Hello @ericlief it looks like you are using Flair 0.3.1 - if I remember correctly, we only added the Portuguese embeddings in version 0.3.2. So you would need to update to this version. 

This code runs for me on 0.3.2: 

```python
from flair.data import Sentence
from flair.embeddings import WordEmbeddings

embeddings = WordEmbeddings('pt')

sentence = Sentence('Desculpe, não falo português')
embeddings.embed(sentence)

for token in sentence:
    print(token.embedding[:10])
```

Could you try this code once you've updated to the latest Flair version?

**Comment by ericlief** [comment]
I still get the error with flair 0.3.2. I have tried with both python 3.6 and 3.7 with (py)torch 0.4.1 and numpy 1.15.2/4:
Traceback (most recent call last):
  File "test-pt-emb.py", line 4, in <module>
    embeddings = WordEmbeddings('pt')
  File "/home/liefe/anaconda3/envs/37/lib/python3.7/site-packages/flair/embeddings.py", line 180, in __init__
    self.precomputed_word_embeddings = gensim.models.KeyedVectors.load(embeddings)
  File "/home/liefe/anaconda3/envs/37/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 122, in load
    return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs)
  File "/home/liefe/anaconda3/envs/37/lib/python3.7/site-packages/gensim/utils.py", line 426, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/home/liefe/anaconda3/envs/37/lib/python3.7/site-packages/gensim/utils.py", line 467, in _load_specials
    val = np.load(subname(fname, attrib), mmap_mode=mmap)
  File "/home/liefe/anaconda3/envs/37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/liefe/anaconda3/envs/37/lib/python3.7/site-packages/numpy/lib/format.py", line 698, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 204692448 into shape (999999,300)

**Comment by alanakbik** [comment]
Hi, unfortunately we cannot reproduce this error on our machines. Perhaps the download of the word embeddings file was corrupted? Could you try deleting the downloaded embedding in your `~/.flair/embeddings/` folder, and then running the code again? This will trigger a fresh download of the model file.

**Comment by MSusik** [comment]
In my case, a similar issue was probably caused by insufficient RAM.
