### ISSUE TITLE
TypeError when loading own model

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#31]
Hi,

I trained an own model on a dataset (using pretty much the same instructions as in `train.py`). For loading the trained model I used:

```python
from flair.data import Sentence
from flair.tagging_model import SequenceTagger

tagger: SequenceTagger = SequenceTagger.load_from_file('resources/taggers/example-ner/final-model.pt')
```

But then the following error message occurs:

```bash
Traceback (most recent call last):
  File "predict.py", line 4, in <module>
    tagger: SequenceTagger = SequenceTagger.load_from_file('resources/taggers/example-ner/final-model.pt')
  File "/flair/flair/tagging_model.py", line 129, in load_from_file
    hidden_size=state['hidden_size'],
TypeError: 'SequenceTagger' object is not subscriptable
```

I hope the `flair` Team could help me :) Thanks!

**Comment by stefan-it** [comment]
The training code looks like:

```python
from flair.data import NLPTaskDataFetcher, TaggedCorpus, NLPTask, Sentence, Token
from flair.embeddings import TextEmbeddings, WordEmbeddings, StackedEmbeddings, \
    CharLMEmbeddings
from typing import List
import torch
import os
import re


def read_conll_2_column_data(path_to_conll_file: str):
    sentences: List[Sentence] = []

    lines: List[str] = open(path_to_conll_file). \
        read().strip().split('\n')

    sentence: Sentence = Sentence()
    for line in lines:

        if line == '':
            sentences.append(sentence)
            sentence: Sentence = Sentence()
        else:
            # print(line)
            fields: List[str] = re.split("\s+", line)
            token = Token(fields[0])
            token.add_tag('ner', fields[1])
            sentence.add_token(token)

    if len(sentence.tokens) > 0:
        sentences.append(sentence)

    return sentences

data_folder = os.path.join('resources', 'tasks', 'az-ner')

sentences_train: List[Sentence] = read_conll_2_column_data(os.path.join(data_folder, 'az-ner.train'))
sentences_dev: List[Sentence] = read_conll_2_column_data(os.path.join(data_folder, 'az-ner.dev'))
sentences_test: List[Sentence] = read_conll_2_column_data(os.path.join(data_folder, 'az-ner.test'))

corpus: TaggedCorpus = TaggedCorpus(sentences_train, sentences_dev, sentences_test)

print(corpus)

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary.idx2item)

# initialize embeddings
embedding_types: List[TextEmbeddings] = [

    WordEmbeddings('de-fasttext')
    ,
    CharLMEmbeddings('german-forward')
    ,
    CharLMEmbeddings('german-backward')
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# initialize sequence tagger
from flair.tagging_model import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

if torch.cuda.is_available():
    tagger = tagger.cuda()

# initialize trainer
from flair.trainer import TagTrain

trainer: TagTrain = TagTrain(tagger, corpus, test_mode=False)

trainer.train('resources/taggers/example-ner', mini_batch_size=16,
              max_epochs=150, save_model=True,
              train_with_dev=True, anneal_mode=True)
```

The code for prediction looks like:

```python
from flair.data import Sentence
from flair.tagging_model import SequenceTagger

tagger: SequenceTagger = SequenceTagger.load_from_file('resources/taggers/example-ner/final-model.pt')

sentence: Sentence = Sentence('Vor einiger Zeit wurde bereits gemeldet , daß das brittische Landwirth schaftsamt den Antrag der schleswig-holsteinischen Interessenten , die Einfuhr von Vieh nach England aus ihrer seit Ende Juli d. I. von der Maul-')
tagger.predict(sentence)

print('Analysing %s' % sentence)
print('\nThe following NER tags are found: \n')
print(sentence.to_tagged_string())
```

I'm using Ubuntu 16.04 + `nvidia-docker`. I'm using `torch` in version *0.4.1.post2* -> maybe this could cause this error? I did a ctrl + c after some time:

```bash
Exiting from training early
saving model
done
```

Thanks so much!

**Comment by alanakbik** [comment]
The code looks good! Could you try training a very small model until it terminates and see if loading works? 

I.e. call 

`corpus.downsample(0.01)`

after creating the corpus object to downsample to one percent of the data. Then, use only WordEmbeddings, i.e. use 

```
embedding_types: List[TextEmbeddings] = [
    WordEmbeddings('de-fasttext')
]
```
to init the embeddings. Then, only train for a few epochs, i.e. 

```
trainer.train('resources/taggers/example-ner', mini_batch_size=16,
              max_epochs=10, save_model=True,
              train_with_dev=True, anneal_mode=True)
```

That should train really quickly. can you then test if you can load it?

**Comment by alanakbik** [comment]
Actually, if you set save_model=False and anneal_model=False its even faster because then it doesn't do checkpoints.

```
trainer.train('resources/taggers/example-ner', mini_batch_size=16,
              max_epochs=10, save_model=False,
              train_with_dev=True, anneal_mode=False)
```

BTW: Release 0.2 (due in a few days) will increase training speed and clarify the training options.

**Comment by stefan-it** [comment]
@alanakbik I think the "Exiting from training early" caused that issue! I tried for one epoch (without interrupting the training) and it worked - so I'm closing the issue here. Thanks for your help :) 

I'm really excited about the new 0.2 release :heart:

**Comment by alanakbik** [comment]
great!
