### ISSUE TITLE
IndexError during training

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#39]
Hi,

a strange bug occured during training of a ner model:

```bash
....................................................................................................16600 of 36276 (0.457603)
..Traceback (most recent call last):
  File "train.py", line 83, in <module>
    train_with_dev=True, anneal_mode=True)
  File "/root/flair/flair/trainer.py", line 80, in train
    loss = self.model.neg_log_likelihood(batch, self.model.tag_type)
  File "/root/flair/flair/tagging_model.py", line 295, in neg_log_likelihood
    forward_score = self._forward_alg(sentence_feats)
  File "/root/flair/flair/tagging_model.py", line 336, in _forward_alg
    alpha = log_sum_exp(terminal_var)
  File "/root/flair/flair/tagging_model.py", line 30, in log_sum_exp
    max_score = vec[0, argmax(vec)]
IndexError: index 1090821856 is out of bounds for dimension 0 with size 14
```
As you can see, that error occured in the middle of an epoch. Here's the `loss.txt` output of previous epochs:

```bash
0	(14:47:06)	2.707507	0	0.100000	DEV   0	_	TEST   	497	acc:  97.17%  p:  74.52%  r:  61.25%  FB1:  67.24
1	(15:17:10)	2.242203	0	0.100000	DEV   0	_	TEST   	567	acc:  96.77%  p:  67.50%  r:  63.59%  FB1:  65.49
2	(15:47:09)	2.186211	0	0.100000	DEV   0	_	TEST   	681	acc:  96.12%  p:  72.25%  r:  62.66%  FB1:  67.11
3	(16:17:10)	2.141665	0	0.100000	DEV   0	_	TEST   	525	acc:  97.01%  p:  74.62%  r:  62.03%  FB1:  67.75
4	(16:47:51)	2.150997	1	0.100000	DEV   0	_	TEST   	549	acc:  96.88%  p:  75.09%  r:  64.53%  FB1:  69.41
```

So the `IndexError` occured during an epoch and previous epochs could be trained sucessfully.

I'm using Torch in version `0.4.1.post2` with 326b3837eabb9b4d528155f36c66009e560756e2.

**Comment by alanakbik** [comment]
Hi Stefan, 
hm that is very strange. Could it be some error in this torch version? Is it possible for you to try this script with torch 0.4.0?

**Comment by alanakbik** [comment]
Hi Stefan
could you try again with the new Flair release and see if the error still occurs?

**Comment by stefan-it** [comment]
Today I tried it with the latest flair release and `0.4.1.post2` and training finished without errors :) So I'm closing here!
