### ISSUE TITLE
Sqlitedict hangs forever when loading Flair Embeddings

### ISSUE THREAD

**Issue by pjtinker** [zalandoresearch/flair#558]
When attempting to load any of the Flair Embeddings, the system hangs indefinitely.

```Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flair.embeddings import FlairEmbeddings
>>> fnf = FlairEmbeddings('news-forward')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/flair/lib/python3.6/site-packages/flair/embeddings.py", line 576, in __init__
    self.cache = SqliteDict(str(cache_path), autocommit=True)
  File "/home/miniconda3/envs/flair/lib/python3.6/site-packages/sqlitedict.py", line 175, in __init__
    self.conn.commit()
  File "/homeminiconda3/envs/flair/lib/python3.6/site-packages/sqlitedict.py", line 525, in commit
    self.select_one('--commit--')
  File "/home/miniconda3/envs/flair/lib/python3.6/site-packages/sqlitedict.py", line 515, in select_one
    return next(iter(self.select(req, arg)))
  File "/home/miniconda3/envs/flair/lib/python3.6/site-packages/sqlitedict.py", line 506, in select
    rec = res.get()
  File "/home/miniconda3/envs/flair/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/miniconda3/envs/flair/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
>>> exit()
```
Other embeddings such as Glove and BERT load with no issues.

**To Reproduce**
`from flair.embeddings import FlairEmbeddings
embedding = FlairEmbeddings('news-forward')`

**Environment:**
 - CentOS 7
 - Flair 0.4.0
 - Torch 1.0.0
 - Python 3.6.8
 - Sqlitedict 1.6.0

**Comment by stefan-it** [comment]
Could you try to use the new *0.4.1* version of `flair`? *0.4.0* is a bit old and a lot of bug fixes were introduced since then :)

**Comment by pjtinker** [comment]
> 
> 
> Could you try to use the new _0.4.1_ version of `flair`? _0.4.0_ is a bit old and a lot of bug fixes were introduced since then :)

That worked, thank you!

**Comment by alanakbik** [comment]
Great, will close the issue but feel free to reopen if you have more questions!
