### ISSUE TITLE
[BUG] A clear Exception/Error message must be thrown while trying to create a Sentence object from an empty string

### ISSUE THREAD

**Issue by Bharat123rox** [zalandoresearch/flair#565]
**Describe the bug**
If one tries to create a `Sentence` object from an empty string, an `UnboundLocalError` of the `index` variable is thrown

**To Reproduce**
```python3
>>> from flair.data import Sentence
>>> s = ''
>>> Sentence(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python36\lib\site-packages\flair\data.py", line 338, in __init__
    index += 1
UnboundLocalError: local variable 'index' referenced before assignment
```

**Expected behavior**
Something like `ValueError: Cannot create a Sentence object from an empty string` or some `Error` or `Exception` mentioning that the string is empty or a `Sentence object "" - 0 tokens`

**Environment (please complete the following information):**
   I feel this is applicable to any OS/version, but anyway:
 - Windows 10
 - flair-0.4.1
 - Python 3.6.8

**Comment by Bharat123rox** [comment]
I believe that the `if text is not None` condition could be changed to `if text` [here](https://github.com/zalandoresearch/flair/blob/master/flair/data.py#L288) to catch the empty string, but I need to know if this could break code elsewhere.
@alanakbik If this is a go, I'm willing to submit a PR 👍
