### ISSUE TITLE
Language model training: Logging error for non-latin language

### ISSUE THREAD

**Issue by ali-h** [zalandoresearch/flair#718]
**Describe the bug**
During the language model training, flair regularly logs sentences generated from the model. In my case, this raises the following error after every epoch:
```
--- Logging error ---
Traceback (most recent call last):
  File "...\torch\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "...\torch\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 28-31: character maps to <undefined>
Call stack:
  File "...flair_lm.py", line 33, in <module>
  File "...\torch\lib\site-packages\flair\trainers\language_model_trainer.py", line 336, in train
    log.info(self.model.generate_text())
Message: (...)
Arguments: ()
```

Note that this doesn't interrupt the training.

**To Reproduce**
Roughly, here's my code:
```python
if __name__ == '__main__':
    # are you training a forward or backward LM?
    is_forward_lm = True

    # load the default character dictionary
    dictionary: Dictionary = Dictionary.load_from_file('chars.pickle')

    # get your corpus, process forward and at the character level
    corpus = TextCorpus(Path('corpus'),
                        dictionary,
                        is_forward_lm,
                        random_case_flip=False,
                        character_level=True)

    # instantiate your language model, set hidden size and number of layers
    language_model = LanguageModel(dictionary,
                                   is_forward_lm,
                                   hidden_size=512,
                                   nlayers=1)

    # train your language model
    trainer = LanguageModelTrainer(language_model, corpus)

    trainer.train(Path('lm'),
                  sequence_length=250,
                  mini_batch_size=10,
                  max_epochs=10)
```

**Environment (please complete the following information):**
 - OS : Windows 10
 - Version : 0.4.1
 - Python: 3.7

**Additional context**
My corpus files are UTF-8 encoded Arabic text files,

**Comment by alanakbik** [comment]
@ali-h thanks for reporting this and for providing the code snippet to reproduce the error! Could you also give us your `chars.pickle` file and a small text file that throws this error? If we can reproduce we can probably fix this.

**Comment by khoaipx** [comment]
I have same issue when building Vietnamese language model. 

```UnicodeEncodeError: 'charmap' codec can't encode character '\u1ed1' in position 34: character maps to <undefined>```

You can download the pickle file [here](https://drive.google.com/file/d/1sKTlfkFx_rdN4WdGPgOWyueXf04YvX_y/view?usp=sharing).
