### ISSUE TITLE
call eval.pl bugs

### ISSUE THREAD

**Issue by TanyaZhao** [zalandoresearch/flair#79]
when the code call eval.pl for evaluation, it causes this bug:

Traceback (most recent call last):
  File "char_lm.py", line 68, in <module>
    max_epochs=150)
  File "E:\users\v-tizhao\vs\flair\trainers\sequence_tagger_trainer.py", line 114, in train
    embeddings_in_memory=embeddings_in_memory)
  File "E:\users\v-tizhao\vs\flair\trainers\sequence_tagger_trainer.py", line 235, in evaluate
    p = run(eval_script, stdout=PIPE, input=eval_data, encoding='utf-8')
  File "E:\users\v-tizhao\anaconda\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\users\v-tizhao\anaconda\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "E:\users\v-tizhao\anaconda\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

btw, I run the code on windows server, 64bit machine.
Could you help me? Thank you !

**Comment by stefan-it** [comment]
The problem is, that a perl script is downloaded and used for the evaluation process. I guess this causes some problems on Windows.

In the upcoming release of `flair` could come with  a pure python implementation of that evaluation script, see  #75 :)

**Comment by TanyaZhao** [comment]
one more questions：how could I get ontonotes 5.0 dataset? 
I saw that in your data_fetcher.py, there is "train.conllu", "test.conllu", "dev.conllu". Are these ontonotes data which have converted into conll format?  Where could I get them?
Could you please tell me the path? 
Thank you very much!

**Comment by stefan-it** [comment]
This repository claims to have the Ontonotes 5.0 in CoNLL format:

https://github.com/ontonotes/conll-formatted-ontonotes-5.0

**Comment by tabergma** [comment]
in release-0.3
