### ISSUE TITLE
AttributeError when trying to fine-tune existing language model

### ISSUE THREAD

**Issue by MarcioPorto** [zalandoresearch/flair#869]
**Describe the bug**
I am getting an AttributeError error when using the linear model fine-tuning approach mentioned in #121.

**To Reproduce**
Here is what my code looks like:

```python
language_model = FlairEmbeddings('news-forward-fast').lm
dictionary = language_model.dictionary
corpus = TextCorpus('path/to/your/corpus', dictionary, is_forward_lm, character_level=True)
trainer = LanguageModelTrainer(language_model, corpus)
trainer.train('resources/taggers/language_model', sequence_length=100, learning_rate=5)
```

And here's the error:

```
...
2019-07-09 13:59:17,735 4713 seconds for train split 1
-----------------------------------------------------------------
AttributeError                  Traceback (most recent call last)
<ipython-input-19-274bb0994985> in <module>
----> 1 trainer.train('resources/taggers/language_model', sequence_length=100, learning_rate=5)

~/Workspace/Deep-Search/deep-search-oec/venv/lib/python3.7/site-packages/flair/trainers/language_model_trainer.py in train(self, base_path, sequence_length, learning_rate, mini_batch_size, anneal_factor, patience, clip, max_epochs, checkpoint, grow_to_sequence_length, **kwargs)
    399                     self.model.eval()
    400 
--> 401                     val_loss = self.evaluate(val_data, mini_batch_size, sequence_length)
    402                     scheduler.step(val_loss)
    403 

~/Workspace/Deep-Search/deep-search-oec/venv/lib/python3.7/site-packages/flair/trainers/language_model_trainer.py in evaluate(self, data_source, eval_batch_size, sequence_length)
    482                 total_loss += len(data) * self.loss_function(output_flat, targets).data
    483                 hidden = self._repackage_hidden(hidden)
--> 484             return total_loss.item() / len(data_source)
    485 
    486     @staticmethod

AttributeError: 'int' object has no attribute 'item'
```
**Environment:**
 - OS: macOS
 - Version: flair-0.4.2

**Comment by MarcioPorto** [comment]
Never mind. My `corpus/test.txt` and `corpus/valid.txt` were accidentally empty.

**Comment by khoaipx** [comment]
I also get this error when I fine tune existing language model. How should I fix it?

```
2019-09-14 22:42:31,654 read text file with 4 lines
2019-09-14 22:42:31,659 read text file with 4 lines
2019-09-14 22:42:31,810 read text file with 78280 lines
2019-09-14 22:42:31,876 shuffled
2019-09-14 22:43:08,835 Sequence length is 100
2019-09-14 22:43:08,888 Split 1  - (22:43:08)
2019-09-14 22:43:14,117 | split   1 /  1 |   100/  359 batches | ms/batch 51.91 | loss  1.49 | ppl     4.44
2019-09-14 22:43:19,242 | split   1 /  1 |   200/  359 batches | ms/batch 51.24 | loss  1.30 | ppl     3.69
2019-09-14 22:43:24,361 | split   1 /  1 |   300/  359 batches | ms/batch 51.18 | loss  1.24 | ppl     3.46
2019-09-14 22:43:27,376 18 seconds for train split 1
Traceback (most recent call last):
  File "main.py", line 192, in <module>
    main()
  File "main.py", line 188, in main
    fine_tune()
  File "main.py", line 180, in fine_tune
    flair_stuff.fine_tune(corpus_dir, stored_dir, model_name=model_name)
  File "/lang_model_builder/flair_stuff.py", line 314, in fine_tune
    checkpoint=True)
  File "/lib/python3.7/site-packages/flair/trainers/language_model_trainer.py", line 428, in train
    val_loss = self.evaluate(val_data, mini_batch_size, sequence_length)
  File "/lib/python3.7/site-packages/flair/trainers/language_model_trainer.py", line 511, in evaluate
    return total_loss.item() / len(data_source)
AttributeError: 'int' object has no attribute 'item'
```
